name: Scrobbler
options:
  bundleIdPrefix: com.tobybarnes
  deploymentTarget:
    macOS: "13.0"
  defaultConfig: Debug
schemes:
  Scrobbler:
    build:
      targets:
        Scrobbler: all
        ScrobblerTests: [test]
    test:
      targets:
        - ScrobblerTests
targets:
  Scrobbler:
    type: application
    platform: macOS
    sources:
      - path: Scrobbler
    settings:
      base:
        PRODUCT_NAME: Scrobbler
        PRODUCT_BUNDLE_IDENTIFIER: com.tobybarnes.scrobbler
        INFOPLIST_FILE: Scrobbler/Info.plist
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        ENABLE_HARDENED_RUNTIME: NO
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_TESTABILITY: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ScrobblerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ScrobblerTests
    dependencies:
      - target: Scrobbler
    settings:
      base:
        PRODUCT_NAME: ScrobblerTests
        PRODUCT_BUNDLE_IDENTIFIER: com.tobybarnes.scrobbler.tests
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Scrobbler.app/Contents/MacOS/Scrobbler"
